apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  
  csi:
    driver: efs.csi.aws.com
    fsType: ext4
    volumeHandle: fs-073d77123471b2917
---
